### ISSUE TITLE
Errors on load

### ISSUE THREAD

**Issue by Gadget111** [echoromeo/hanobo#32]
I have been using this for about a year with no issues.
Since yesterday, my climate entities have disappeared. Suspected an issue after core upgrade, so I have restored a snapshot, this has not helped. 

2021-05-20 07:02:10 INFO (SyncWorker_3) [custom_components.nobo_hub.climate] discovering and connecting to 099
2021-05-20 07:02:11 ERROR (MainThread) [homeassistant.components.climate] Error while setting up nobo_hub platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 231, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args,**self.kwargs)
  File "/config/custom_components/nobo_hub/climate.py", line 81, in setup_platform
    hub = nobo(serial=host)
  File "/usr/local/lib/python3.8/site-packages/pynobo.py", line 206, in __init__
    self._loop = asyncio.get_event_loop() if loop is None else loop
  File "/usr/local/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'SyncWorker_3'

Any idea as to what has gone wrong?
Many thanks

**Comment by Gadget111** [comment]
Issue found. Updated requirements in manifest. Comparitor >= changed to ==
