### ISSUE TITLE
Error after installation

### ISSUE THREAD

**Issue by danholthoejgaard** [echoromeo/hanobo#40]
Got this error right after installation:

Logger: homeassistant.components.climate
Source: custom_components/nobo_hub/climate.py:84
Integration: Climate (documentation, issues)
First occurred: 5:23:38 PM (1 occurrences)
Last logged: 5:23:38 PM

Error while setting up nobo_hub platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 250, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nobo_hub/climate.py", line 84, in setup_platform
    hub = nobo(serial=host, ip=ip, discover=False)
  File "/usr/local/lib/python3.10/site-packages/pynobo.py", line 303, in __init__
    self._loop = asyncio.get_event_loop() if loop is None else loop
  File "/usr/local/lib/python3.10/asyncio/events.py", line 656, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'SyncWorker_3'.

**Comment by oyvindwe** [comment]
Hi! Looks like you have installed version 1.2.0 or newer of `pynobo`. This current HACS version doesn't support the async version - try to revert to `pynobo` version 1.1.2

**Comment by pioo1979** [comment]
I have the following log message. I have chosen the 1.1.2 version in the HACS install, is it still installed 1.1.3 version? 
how can I install the oldest one?
thanks
david

Logger: homeassistant.components.climate
Source: custom_components/nobo_hub/climate.py:84
Integration: Climate (documentation, issues)
First occurred: 12:14:00 PM (1 occurrences)
Last logged: 12:14:00 PM

Error while setting up nobo_hub platform for climate
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 281, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/nobo_hub/climate.py", line 84, in setup_platform
    hub = nobo(serial=host, ip=ip, discover=False)
  File "/usr/local/lib/python3.10/site-packages/pynobo.py", line 188, in __init__
    raise ValueError('Could not connect, no valid serial number provided')
ValueError: Could not connect, no valid serial number provided

**Comment by oyvindwe** [comment]
If you upgrade to Home Assistant 2022.10, this integration will be included (_remove_ the custom component first).

If installing via Hacs, select version *1.1.3* of the _integration_. This should give you the correct version of the `pynobo` library.
